version: '3.7'
networks:
  net:
    driver: bridge

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.acme.se`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.options=default'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.acme.se'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - TZ=Asia/Tehran
  
  traefik:
    image: traefik:2.4
    container_name: traefik
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.acme.se`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.options=default'
      - 'traefik.http.routers.api.middlewares=authelia'
    ports:
      - 80:80
      - 443:443
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.file.filename=/etc/traefik/traffic.toml'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--log.level=DEBUG'

  webserver:
      image: webserver-image
      container_name: webserver
      build:
        context: ./webserver
      networks:
        - net
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.webserver.rule=Host(`webserver.acme.se`)'
        - 'traefik.http.routers.webserver.entrypoints=https'
        - 'traefik.http.routers.webserver.tls=true'
        - 'traefik.http.routers.webserver.tls.options=default'
        - 'traefik.http.routers.webserver.middlewares=authelia'
      expose:
        - 80
      restart: unless-stopped
