
networks:
  net:
    driver: bridge

services:
  authelia:
    image: 'authelia/authelia'
    container_name: 'authelia'
    volumes:
      - './authelia/config:/config'
    ports: 
      - "9091:9091"
    networks:
      net: {}
  
  traefik:
    image: 'traefik:v3.2.3'
    container_name: 'traefik'
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/traefik"
    command:
        - "--api=true"
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--providers.file.filename=./traefik/config/traefik.toml"
        - "--providers.file.watch=true"
        - "--log.level=DEBUG"
    labels:
      traefik.http.routers.api.entryPoints: 'https'
      traefik.enable: 'true'
      traefik.http.routers.api.tls.certresolver: 'letsencrypt'
      traefik.http.routers.api.tls.options: 'default'




  webserver:
    build:
      context: './webserver'
      dockerfile: 'Dockerfile'
    container_name: 'webserver_acme'
    ports: 
      - "3000:3000"
    networks:
      net: {}



