services:
  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges=true'
    networks:
      proxy:
        aliases:
          - 'authelia.acme.se'
      authelia: {}
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: 'America/Los_Angeles'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/config/traefik.yaml:/traefik.yaml:ro'
      - './traefik/data/:/data'
      - './traefik/logs:/logs'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.dashboard.rule: 'Host(`traefik.valid-domain.com`)'
      traefik.http.routers.dashboard.entrypoints: 'https'
      traefik.http.routers.dashboard.middlewares: 'authelia'
      traefik.http.routers.dashboard.service: 'api@internal'

  whoami:
    image: 'traefik/whoami'
    restart: 'unless-stopped'
    container_name: 'whoami'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami.rule: 'Host(`whoami.valid-domain.com`)'
      traefik.http.routers.whoami.entrypoints: 'https'
    networks:
      proxy: {}

  authelia:
    image: 'authelia/authelia:4.38'
    container_name: 'authelia'
    volumes:
      - './authelia/secrets:/secrets:ro'
      - './authelia/config:/config'
      - './authelia/logs:/var/log/authelia/'
    networks:
      authelia: {}
    labels:
      ## Expose Authelia through Traefik
      traefik.enable: 'true'
      traefik.docker.network: 'authelia'
      traefik.http.routers.authelia.rule: 'Host(`authelia.acme.se`)'
      traefik.http.routers.authelia.entrypoints: 'https'
      ## Setup Authelia ForwardAuth Middlewares
      traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    environment:
      TZ: 'America/Los_Angeles'
      X_AUTHELIA_CONFIG_FILTERS: 'template'

  whoami-secure:
    image: 'traefik/whoami'
    restart: 'unless-stopped'
    container_name: 'whoami-secure'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami-secure.rule: 'Host(`whoami-secure.example.com`)'
      traefik.http.routers.whoami-secure.entrypoints: 'https'
      traefik.http.routers.whoami-secure.middlewares: 'authelia'
    networks:
      proxy: {}

  webserver:
    build:
      context: './webserver'
      dockerfile: 'Dockerfile'
    container_name: 'webserver_acme'
    networks:
      proxy: {}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webserver.rule=Host(`webserver.acme.se`)'
      - 'traefik.http.routers.webserver.entrypoints=https'
      - 'traefik.http.routers.webserver.middlewares=authelia'
      - 'traefik.http.routers.webserver.tls=true'

networks:
  proxy:
    external: true
    name: 'proxy'
  authelia:
    name: 'authelia'