services:
  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/traefik
    command:
        - "--api=true"
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--entrypoints.webserver-entrypoint.address=:3000"
        - "--providers.file.filename=/traefik/traefik.toml"
        - "--providers.file.watch=true"
        - "--log.level=DEBUG"

  authelia:
    image: 'authelia/authelia:latest'
    container_name: 'authelia'
    volumes:
      - './authelia/config:/config'
    ports: 
      - "9091:9091"
    networks:
      - net

  webserver:
    build:
      context: './webserver'
      dockerfile: 'Dockerfile'
    container_name: 'webserver_acme'
    ports: 
      - "3000:3000"
    networks:
    - net


networks:
  net:
    bridge: true
