version: '3.8'

networks:
  acme_network:
    driver: bridge
  
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    networks:
      - acme_network
    ports:
      - 9091:9091
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.acme.se`)"
      - "traefik.http.routers.authelia.entrypoints=https"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=http://authelia.acme.se:9091"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email"
    expose:  
      - 9091
    


  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
       - '--api'
       - '--providers.docker=true'
       - '--providers.docker.exposedByDefault=false'
       - '--providers.file.filename=/etc/traefik/certificates.yml'
       - '--entrypoints.http=true'
       - '--entrypoints.http.address=:80'
       - '--entrypoints.http.http.redirections.entrypoint.to=https'
       - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
       - '--entrypoints.https=true'
       - '--entrypoints.https.address=:443'
       - '--log=true'
       - '--log.level=DEBUG'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
    networks:
      - acme_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.acme.se`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.middlewares=authelia@docker"
      - "traefik.http.routers.api.tls.options=default"
      - "traefik.http.routers.api.tls=true"
      - 'traefik.http.routers.api.service=api@internal'

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - acme_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`webserver.acme.se`)"
      - "traefik.http.routers.webserver.entrypoints=https"
      - "traefik.http.routers.webserver.middlewares=authelia@docker"
      - 'traefik.http.routers.webserver.tls=true'
      - 'traefik.http.routers.webserver.tls.options=default' 
      - 'traefik.http.routers.webserver.service=api@internal'

    expose: 
      - 3000
    


      