services:
  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    networks:
      - 'net'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik-config:/traefik
    command:
        - "--api=true"
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--entrypoints.webserver-entrypoint.address=:3000"
        - "--providers.file.filename=/traefik/traefik.toml"
        - "--providers.file.watch=true"
        - "--log.level=DEBUG"


  
      

  authelia:
    image: 'authelia/authelia:latest'
    container_name: 'authelia'
    volumes:
      - './authelia/config:/config'
    networks:
      - 'net'
    labels:
      ## Expose Authelia through Traefik
      traefik.enable: 'true'
      traefik.docker.network: 'authelia'
      traefik.http.routers.authelia.rule: 'Host(`authelia.acme.se`)'
      traefik.http.routers.authelia.entrypoints: 'https'
      ## Setup Authelia ForwardAuth Middlewares
      traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Name,Remote-Email'



  webserver:
    build:
      context: './webserver'
      dockerfile: 'Dockerfile'
    container_name: 'webserver_acme'
    networks:
    - 'net'


networks:
  net:
    driver: bridge
