services:
  traefik:
    image: 'traefik:v3.2.3'
    container_name: 'traefik'
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/traefik"
    command:
        - "--api=true"
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--providers.file.filename=./traefik/config/traefik.toml"
        - "--providers.file.watch=true"
        - "--log.level=DEBUG"
    labels:
      traefik.http.routers.api.entryPoints: 'https'


  authelia:
    image: 'authelia/authelia'
    container_name: 'authelia'
    volumes:
      - './authelia/config:/config'
    ports: 
      - "9091:9091"
    networks:
      authelia: {}


  webserver:
    build:
      context: './webserver'
      dockerfile: 'Dockerfile'
    container_name: 'webserver_acme'
    ports: 
      - "3000:3000"
    networks:
    - net


networks:
  net:
    driver: bridge
  authelia:
    name: 'authelia'
