jwt_secret: a_very_important_secret
identity_validation:


server:
  address: tcp://0.0.0.0:9091

log:
  level: debug

totp:
  issuer: authelia.acme.se

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt: 16
  # ldap:
  #   implementation: custom
  #   address: ldap://192.168.1.177
  #   start_tls: false
  #   tls:
  #     skip_verify: false
  #     minimum_version: TLS1.2
  #   base_dn: dc=acme,dc=se
  #   additional_users_dn: cn=users,cn=accounts
  #   users_filter: (&({username_attribute}={input})(objectClass=person))
  #   additional_groups_dn: cn=groups,cn=accounts
  #   groups_filter: (&(member=uid={input},cn=users,cn=accounts,dc=acme,dc=se)(objectclass=groupofnames))
  #   attributes:
  #     username: uid
  #     display_name: givenName
  #     group_name: cn
  #     mail: mail
  #   user: uid=admin,cn=users,cn=accounts,dc=acme,dc=se
  #   password: NilsSmokesCoke2025!

access_control:
  default_policy: deny
  rules:
    - domain: webserver.acme.se
      policy: one_factor
    - domain: traefik.acme.se
      policy: one_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: acme.se
  cookies:
    - domain: acme.se
      default_redirection_url: https://webserver.acme.se
      secure: true

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt