http:
  routers:
    authelia:
      rule: "Host(`authelia.acme.se`)"
      entryPoints:
        - websecure
      service: authelia

    webserver:
      rule: "Host(`webserver.acme.se`)"
      entryPoints:
        - websecure
      service: webserver
      middlewares:
        - authelia

    traefik:
      rule: "Host(`traefik.acme.se`)"
      entryPoints:
        - websecure
      service: api@internal

  services:
    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091

    webserver:
      loadBalancer:
        servers:
          - url: http://webserver:80

  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://authelia.acme.se
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups