http:
  routers:
    pve1:
      entryPoints:
        - "https"
      rule: "Host(`traefik.acme.se`)"
      middlewares:
        - aut
        - default-headers
      tls: {}
      service: pve1
  services:
    pve1:
      loadBalancer:
        servers:
                - url: "http://192.168.1.230:9090"
        passHostHeader: true

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    aut:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://authelia.acme.se"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
