[entryPoints]
  [entryPoints.http]
    address = ":8080"
    [entryPoints.http.proxyProtocol]
      trustedIPs = ["192.168.1.0/24", "172.16.0.0/12"]
  [entryPoints.https]
    address = ":8443"
    [entryPoints.https.proxyProtocol]
      trustedIPs = ["192.168.1.0/24", "172.16.0.0/12"]

[providers]
  [providers.docker]
    endpoint = "unix://var/run/docker.sock"
    exposedByDefault = false
    network = "net"
    defaultRule = "Host(`{{ normalize .Name }}.acme.se`)"
  [providers.file]
    filename = "/etc/traefik/config.yml"

[api]
  dashboard = true
  insecure = true

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
    entryPoint = "web"