[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    filename = "/traefik/config.yaml"

[api]
  dashboard = true
  insecure = true

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
    entryPoint = "web"