[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entryPoint]
          to = "https"
          scheme = "https"
  [entryPoints.https]
    address = ":443"

[http.routers]
  [http.routers.webserver]
    rule = "Host(`webserver.acme.se`)"
    service = "webserver"
    middlewares = ["authelia@file"]
    [http.routers.webserver.tls]
  [http.routers.authelia]
    rule = "Host(`authelia.acme.se`)"
    service = "authelia"
    [http.routers.authelia.tls]
  [http.routers.api]
    rule = "Host(`traefik.acme.se`)"
    service = "api@internal"
    middlewares = ["authelia@file"]

[http.services]
  [http.services.webserver]
    [[http.services.webserver.loadBalancer.servers]]
      url = "http://webserver.acme.se:3000/"
  [http.services.authelia]
    [[http.services.authelia.loadBalancer.servers]]
      url = "http://authelia:9091/"

[http.middlewares]
  [http.middlewares.authelia.forwardAuth]
    address = "http://authelia:9091/api/verify?rd=http://authelia.acme.se:9091"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Name", "Remote-Email"]

[log]
  level = "DEBUG"

[accessLog]
