[http.routers]
  [http.routers.webserver]
    entryPoints = ["webserver"]
    rule = "Host(`webserver.acme.se`)"
    service = "webserver-service"
    middlewares = "authelia"
    [http.routers.webserver.tls]
  [http.routers.authelia]
    entryPoints = ["authelia"]
    rule = "Host(`authelia.acme.se`)"
    service = "authelia-service"
    [http.routers.authelia.tls]



[http.services]
  [http.services.webserver-service]
    [[http.services.webserver.loadBalancer.servers]]
      url = "http://webserver.acme.se:3000/"
  [http.services.authelia-service]
    [[http.services.authelia.loadBalancer.servers]]
      url = "http://authelia:9091/"

[http.middlewares]
  [http.middlewares.authelia.forwardAuth]
    address = "http://authelia:9091/api/verify?rd=https://authelia.acme.se:9091/"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Name", "Remote-Email"]