## Base Traefik configuration
api:
  dashboard: true
  debug: false
  insecure: false

log:
  level: 'INFO'
accessLog:
  filePath: '/logs/access.log'

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
       entryPoint:
         to: 'https'
         scheme: 'https'
         permanent: true
  https:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false



tls:
  options:
    default:
      minVersion: 'VersionTLS12'
      cipherSuites:
        - 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
        - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
        - 'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305'
        - 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305'