server.port: 9091
log.level: debug
jwt_secret: insecure_secret
authentication_backend:
  ldap:
    implementation: activedirectory
    url: ldap://ipasrv.acme.se
    timeout: 5s
    start_tls: false
    base_dn: DC=amce,DC=se
#    additional_users_dn: OU=Users,OU=COMPANY
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)(!pwdLastSet=0))
    username_attribute: sAMAccountName
    mail_attribute: mail
    display_name_attribute: displayName
    groups_filter: (&(member:1.2.840.113556.1.4.1941:={dn})(objectClass=group)(objectCategory=group))
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: uid=admin,cn=users,cn=accounts,dc=acme,dc=se
    password: NilsSmokesCoke2025!
totp:
  disable: true

session:
  name: authelia_session
  domain: acme.se
  same_site: lax
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

access_control:
  default_policy: one_factor
  rules:
    - domain: traefik.acme.se
      policy: bypass
    - domain: webserver.acme.se
      policy: two_factor

notifier:
  filesystem:
    filename: /config/notification.txt